server:
  port: 8081
  servlet:
    context-path: /api/users

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  secret: "my-ultra-secure-and-very-long-secret-key-for-jwt-1234567890"
  expiration: 86400000 # 24 horas en milisegundos

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha